import { GroupElement, MAC, ZKP } from 'cashu_kvac';
import { CheckStateEnum } from '../responses';

/**
 * Payload that needs to be sent to the mint when checking for spendable proofs
 */
export type CheckStatePayload = {
	/**
	 * The nullifiers of the coins to be checked.
	 */
	nullifiers: Array<GroupElement>;
};

export type KvacIssuedMac = {
	/**
	 * MAC generated by the Mint
	 */
	mac: MAC;
	/**
	 * Commitments for which the MAC was generated
	 */
	commitments: [GroupElement, GroupElement];
	/**
	 * ID of the keyset used to generate the MAC
	 */
	keyset_id: string;
	/**
	 * (optional) the quote ID if this was a mint/melt request
	 */
	quote_id?: string;
	/**
	 * Zero-Knowledge proof that MAC was generated with the keys of keyset_id
	 */
	issuance_proof: ZKP;
};

export type KvacCoinState = {
	/**
	 * Nullifiers of the queried coins
	 */
	nullifier: GroupElement;
	/**
	 * state
	 */
	state: CheckStateEnum;
};
